# Generated by Django 2.2.5 on 2019-10-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191009_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='reported',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
