# Generated by Django 2.2.5 on 2019-10-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_employee_lead_manager'),
        ('core', '0003_auto_20191009_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manager',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.Manager'),
            preserve_default=False,
        ),
    ]
