# Generated by Django 2.2.5 on 2019-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191010_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
