# Generated by Django 2.2.5 on 2019-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191118_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('analysis', 'analysis'), ('resolving', 'resolving'), ('implementing', 'implementing'), ('testing', 'testing'), ('done', 'done')], default='analysis', max_length=255),
        ),
    ]
