# Generated by Django 2.2.5 on 2019-11-28 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191118_1322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('change_ticket_state', 'Can change the state of tickets')]},
        ),
    ]
