# Generated by Django 2.2.5 on 2019-11-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191128_0822'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('change_state_ticket', 'Can change the state of tickets')]},
        ),
    ]
