# Generated by Django 2.2.5 on 2019-11-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191128_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.AddField(
            model_name='task',
            name='solution_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
