# Generated by Django 2.2.5 on 2019-12-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191128_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('resolving', 'resolving'), ('pending', 'pending'), ('rejected', 'rejected'), ('done', 'done')], default='pending', max_length=255),
        ),
    ]
